### ISSUE TITLE
[enhancement] OO usage of shell-command

### ISSUE THREAD

**Issue by schmunk42** [omauger/docker-compose-php#13]
Hi,

so this is not a big deal, but I wanted to mention, that mikehaertl/shell-command has a nice object-oriented way for building commands.

See this for an example: https://github.com/dmstr/yii2-db/blob/40da169057ee35c9877a714bbf0150fa6cb0fbdb/console/controllers/MysqlController.php#L250-L253

Related discussion... https://github.com/mikehaertl/php-shellcommand/issues/11

This is just nice to have, not a real bug.
Great to see the progress here...

Regards.

**Comment by omauger** [comment]
Hi, 

Thanks for the informations.
I have integrated it in the version in progress.

Regards.
